import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";
import { Toaster } from "react-hot-toast";
import TanstackProvider from "@/providers/tanstack-provider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Juba Hospitality",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TanstackProvider>
      <html lang="en">
        <body
          className={`${poppins.className}  antialiased pt-[80px]`}
          suppressHydrationWarning={true}
        >
          {children}
          <Toaster
            toastOptions={{
              className: "text-sm capitalize",
            }}
          />
          <ReactQueryDevtools initialIsOpen={false} />
        </body>
      </html>
    </TanstackProvider>
  );
}
